version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Maps port 80 in the container to port 8080 on the host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=EmpDemoDb;Username=postgres;Password=sa@123;
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa@123
      - POSTGRES_DB=EmpDemoDb
    ports:
      - "5432:5432"
